apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskapp.fullname" . }}-app
  labels:
    {{- include "taskapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "taskapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "taskapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: {{ include "taskapp.serviceAccountName" . }}
      containers:
        - name: app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "taskapp.fullname" . }}
            - secretRef:
                name: {{ include "taskapp.fullname" . }}
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "taskapp.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: app
                topologyKey: kubernetes.io/hostname
