apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskapp.fullname" . }}
  labels:
    {{- include "taskapp.labels" . | nindent 4 }}
data:
  NODE_ENV: production
  SITE_NAME: {{ .Values.config.siteName }}
  DEFAULT_LOCALE: {{ .Values.config.defaultLocale }}
  DEFAULT_ACCENT: {{ .Values.config.defaultAccent }}
  DATABASE_URL: postgresql://taskapp:$(DB_PASSWORD)@{{ include "taskapp.fullname" . }}-pgbouncer:6432/taskapp
  REDIS_URL: redis://{{ include "taskapp.fullname" . }}-redis:6379
  S3_ENDPOINT: http://{{ include "taskapp.fullname" . }}-minio:9000
