apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskapp.fullname" . }}
  labels:
    {{- include "taskapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | default "changeme" | quote }}
  auth-secret: {{ .Values.secret.authSecret | default "changeme" | quote }}
  s3-access-key: {{ .Values.secret.s3AccessKey | default "changeme" | quote }}
  s3-secret-key: {{ .Values.secret.s3SecretKey | default "changeme" | quote }}
  smtp-host: {{ .Values.secret.smtpHost | default "" | quote }}
  smtp-port: {{ .Values.secret.smtpPort | default "587" | quote }}
  smtp-user: {{ .Values.secret.smtpUser | default "" | quote }}
  smtp-password: {{ .Values.secret.smtpPassword | default "" | quote }}
  smtp-from: {{ .Values.secret.smtpFrom | default "" | quote }}
  ldap-url: {{ .Values.secret.ldapUrl | default "" | quote }}
  ldap-bind-dn: {{ .Values.secret.ldapBindDn | default "" | quote }}
  ldap-bind-password: {{ .Values.secret.ldapBindPassword | default "" | quote }}
  ldap-search-base: {{ .Values.secret.ldapSearchBase | default "" | quote }}
  ldap-default-role: {{ .Values.secret.ldapDefaultRole | default "member" | quote }}
  saml-entity-id: {{ .Values.secret.samlEntityId | default "" | quote }}
  saml-idp-metadata-url: {{ .Values.secret.samlIdpMetadataUrl | default "" | quote }}
