apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskapp.fullname" . }}-socket
  labels:
    {{- include "taskapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: socket
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: ws
  selector:
    {{- include "taskapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: socket
